name: melart
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - charset-normalizer=2.0.4
  - click=8.1.7
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.2
  - idna=3.7
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - jedi=0.19.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.15
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.12.4
  - python-dateutil=2.9.0
  - python-dotenv=0.21.0
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.32.2
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024a
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - blis==0.7.11
      - catalogue==2.0.10
      - cloudpathlib==0.18.1
      - confection==0.1.5
      - contourpy==1.3.0
      - cycler==0.12.1
      - cymem==2.0.8
      #- en-core-web-sm==3.7.1
      - fonttools==4.54.1
      - jinja2==3.1.4
      - kiwisolver==1.4.7
      - langcodes==3.4.0
      - language-data==1.2.0
      - marisa-trie==1.2.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - murmurhash==1.0.10
      - pillow==10.4.0
      - pip==24.1.1
      - preshed==3.0.9
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - pyparsing==3.1.4
      - rich==13.7.1
      - setuptools==70.1.1
      - shellingham==1.5.4
      - smart-open==7.0.4
      - spacy==3.7.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - thinc==8.2.5
      - tqdm==4.66.4
      - typer==0.12.3
      - wasabi==1.1.3
      - weasel==0.4.1
      - wrapt==1.16.0
