name: melart
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.6.2
  - charset-normalizer=2.0.4
  - click=8.1.7
  - expat=2.6.2
  - idna=3.7
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.14
  - pip
  - pysocks=1.7.1
  - python=3.12.4
  - python-dotenv=0.21.0
  - readline=8.2
  - requests=2.32.2
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - urllib3=2.2.2
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - blis==0.7.11
      - catalogue==2.0.10
      - cloudpathlib==0.18.1
      - confection==0.1.5
      - cymem==2.0.8
      #- en-core-web-sm==3.7.1
      - jinja2==3.1.4
      - langcodes==3.4.0
      - language-data==1.2.0
      - marisa-trie==1.2.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - murmurhash==1.0.10
      - numpy==1.26.4
      - packaging==24.1
      - pip==24.1.1
      - preshed==3.0.9
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - pygments==2.18.0
      - rich==13.7.1
      - setuptools==70.1.1
      - shellingham==1.5.4
      - smart-open==7.0.4
      - spacy==3.7.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - thinc==8.2.5
      - tqdm==4.66.4
      - typer==0.12.3
      - typing-extensions==4.12.2
      - wasabi==1.1.3
      - weasel==0.4.1
      - wrapt==1.16.0
